### ISSUE TITLE
The error of HairMix_run

### ISSUE THREAD

**Issue by sarahxinxi** [papagina/HairNet_DataSetGeneration#3]
![image](https://user-images.githubusercontent.com/35719221/75028142-b71dab00-54da-11ea-9365-88eb090699a5.png)
![image](https://user-images.githubusercontent.com/35719221/75028187-cc92d500-54da-11ea-97ef-e781972b6127.png)
I met the problem Segmentation fault (core dumped) when I running the programm HairMix_run.

**Comment by alexyz-0** [comment]
Hi, you closed this thread. Did you solve it and if so, could you recall how you did it?
